name: Smoke Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    container:
      image: php:8.0.2-cli-buster

    steps:
      - uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Install PHPUnit
        shell: bash
        run: |
          curl -Lo ./bin/phpunit-9.phar https://phar.phpunit.de/phpunit-9.phar
          chmod +x bin/phpunit-9.phar

      - name: Build junit-to-json
        shell: bash
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
            apt-get install -y nodejs && \
            npm install -g npm@7.5.4

          cd junit-to-json
          npm install

      - name: Smoke Test
        run: |
          ./bin/run.sh hello-world ./test/hello-world ./test

      - name: Verify files present
        run: ./.github/bin/check_files.sh
