name: Smoke Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    container:
      image: php:8.0.2-cli-buster

    steps:
      - uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Install PHPUnit
        shell: bash
        run: |
          curl -Lo ./bin/phpunit-9.phar https://phar.phpunit.de/phpunit-9.phar
          chmod +x bin/phpunit-9.phar

      - name: Build junit-to-json
        shell: bash
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
            apt-get install -y nodejs && \
            npm install -g npm@7.5.4

          cd junit-to-json
          npm install

      - name: Install Other Deps
        shell: bash
        run: |
          apt-get install -y jo

      - name: Smoke Test
        run: |
          ./bin/run.sh hello-world ./test/hello-world ./test

      - name: Verify files present
        run: ./.github/bin/check_files.sh
