name: Test JUnit-to-JSON

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Update NPM
        run: |
          npm install -g npm@7.5.4

      - name: Build junit-to-json
        run: |
          cd junit-to-json && npm install

      - name: Jest tests
        run: |
          cd junit-to-json && npm run test
